#!/bin/sh
# Ensures a self-hosted admin key exists at local/.admin-key (gitignored).
# Idempotent: does nothing if the key file already exists.
set -eu
cd "$(dirname "$0")"

if [ ! -f .admin-key ]; then
  # Wait for the backend to accept exec (dashboard waits on healthcheck too).
  for _ in $(seq 1 30); do
    if docker compose -f docker-compose.yml exec backend ./generate_admin_key.sh > .admin-key.tmp 2>/dev/null; then
      break
    fi
    sleep 2
  done

  # Keep only the key line (output is "Admin key:\n<key>").
  grep -o 'convex-self-hosted|[^[:space:]]*' .admin-key.tmp | tail -1 > .admin-key
  rm -f .admin-key.tmp
  chmod 600 .admin-key
fi

# CLI deployment selector for `convex dev --env-file local/.env`.
# Kept out of .env.local so the cloud setup is never touched.
{
  echo "# Generated by 'pnpm local:up'. Points the Convex CLI at the local backend."
  echo "CONVEX_SELF_HOSTED_URL=${CONVEX_SELF_HOSTED_URL:-http://127.0.0.1:3210}"
  echo "CONVEX_SELF_HOSTED_ADMIN_KEY=$(cat .admin-key)"
} > .env
chmod 600 .env
echo "Wrote local/.admin-key + local/.env (do not commit)"
